name: TEST

on:
  workflow_dispatch:

env:
  JAVA_VERSION: '11'
  JAVA_DISTRIBUTION: 'microsoft'
  ARTIFACT_PATH: 'platform-server/target/*.jar'
  IMAGE_NAME: 'java-service'

jobs:
  build-and-sast-sca-scan:
    name: Build and SAST & SCA Scan
    runs-on: ubuntu-latest
    if: github.repository == 'ADProject-C24G2/collaborative-practice-platform-back-end'
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          cache: 'maven'

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: 'java'

      - name: Set Cache Week
        id: date
        run: echo "week=$(date +%Y-%U)" >> $GITHUB_OUTPUT

      - name: Cache NVD data
        uses: actions/cache@v4
        with:
          path: ~/.dependency-check/data
          key: ${{ runner.os }}-nvd-data-${{ steps.date.outputs.week }}
          restore-keys: |
            ${{ runner.os }}-nvd-data-

      - name: Build and Run OWASP Dependency Check for SCA
        continue-on-error: true
        run: mvn -B clean install org.owasp:dependency-check-maven:check -DnvdApiKey=${{ secrets.NVD_API_KEY }}

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:java"

      - name: Upload SCA Scan Report
        uses: actions/upload-artifact@v4
        with:
          name: all-sca-reports
          path: '**/target/dependency-check-report.html'

      - name: Upload CodeQL SAST Report
        uses: actions/upload-artifact@v4
        with:
          name: codeql-sast-report
          path: /home/runner/work/collaborative-practice-platform-back-end/results/java.sarif