name: Test

on:
  workflow_dispatch:

env:
  JAVA_VERSION: '11'
  JAVA_DISTRIBUTION: 'microsoft'
  ARTIFACT_PATH: 'platform-server/target/*.jar'
  IMAGE_NAME: 'java-service'

jobs:
  build-and-sast-sca-scan:
    name: Build and SAST & SCA Scan
    runs-on: ubuntu-latest
    if: github.repository == 'ADProject-C24G2/collaborative-practice-platform-back-end'
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          cache: 'maven'

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: 'java'

      - name: Build with Maven
        run: mvn -B clean install

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:java"

      - name: Upload CodeQL SAST Report
        uses: actions/upload-artifact@v4
        with:
          name: codeql-sast-report
          path: ../results/java.sarif